// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/memcash_messages.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{6, 0}
}

type Status struct {
	Error                bool     `protobuf:"varint,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SetDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Expiration           int64    `protobuf:"varint,3,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataRequest) Reset()         { *m = SetDataRequest{} }
func (m *SetDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetDataRequest) ProtoMessage()    {}
func (*SetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{1}
}

func (m *SetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataRequest.Unmarshal(m, b)
}
func (m *SetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataRequest.Marshal(b, m, deterministic)
}
func (m *SetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataRequest.Merge(m, src)
}
func (m *SetDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetDataRequest.Size(m)
}
func (m *SetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataRequest proto.InternalMessageInfo

func (m *SetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetDataRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetDataRequest) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type GetDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{2}
}

func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (m *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(m, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DataResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Expiration           int64    `protobuf:"varint,4,opt,name=Expiration,proto3" json:"Expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{3}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DataResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DataResponse) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type Response struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{5}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebbcbe7cf9c81086, []int{6}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*SetDataRequest)(nil), "SetDataRequest")
	proto.RegisterType((*GetDataRequest)(nil), "GetDataRequest")
	proto.RegisterType((*DataResponse)(nil), "DataResponse")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*HealthCheckRequest)(nil), "HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "HealthCheckResponse")
}

func init() { proto.RegisterFile("pb/memcash_messages.proto", fileDescriptor_ebbcbe7cf9c81086) }

var fileDescriptor_ebbcbe7cf9c81086 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x51, 0x4b, 0x3a, 0x41,
	0x14, 0xc5, 0xff, 0xe3, 0xfe, 0x73, 0xf5, 0x6e, 0x99, 0x4c, 0x3d, 0x6c, 0x2f, 0x25, 0xf3, 0x24,
	0x04, 0x2b, 0xd9, 0x4b, 0xf8, 0x58, 0x89, 0x85, 0xb4, 0xc2, 0x6c, 0x59, 0xf4, 0x22, 0xa3, 0x5c,
	0x54, 0x52, 0x77, 0x9a, 0x19, 0xad, 0x3e, 0x44, 0xdf, 0x39, 0xd6, 0x71, 0x28, 0xc9, 0xa8, 0xb7,
	0xfd, 0xdd, 0xbd, 0xe7, 0xdc, 0x73, 0x60, 0xe0, 0x40, 0xf6, 0x6b, 0x53, 0x9c, 0x0e, 0x84, 0x1e,
	0xf5, 0xa6, 0xa8, 0xb5, 0x18, 0xa2, 0x8e, 0xa4, 0x4a, 0x4d, 0xca, 0xce, 0x20, 0x9f, 0x18, 0x61,
	0xe6, 0x9a, 0xee, 0xc3, 0x56, 0x53, 0xa9, 0x54, 0x85, 0xa4, 0x42, 0xaa, 0x05, 0x6e, 0x81, 0x86,
	0xe0, 0xdf, 0x58, 0x45, 0x98, 0xab, 0x90, 0x6a, 0x91, 0x3b, 0x64, 0x0f, 0x50, 0x4a, 0xd0, 0x5c,
	0x0a, 0x23, 0x38, 0x3e, 0xcf, 0x51, 0x1b, 0x5a, 0x06, 0xaf, 0x8d, 0x6f, 0x4b, 0x7d, 0x91, 0x67,
	0x9f, 0x99, 0x67, 0x57, 0x4c, 0xe6, 0x4e, 0x6b, 0x81, 0x1e, 0x02, 0x34, 0x5f, 0xe5, 0x58, 0x09,
	0x33, 0x4e, 0x67, 0xa1, 0x57, 0x21, 0x55, 0x8f, 0x7f, 0x99, 0x30, 0x06, 0xa5, 0xd6, 0x2f, 0xce,
	0xec, 0x05, 0xb6, 0xed, 0x82, 0x96, 0xe9, 0x4c, 0x23, 0x3d, 0x72, 0x3d, 0x96, 0x4b, 0x41, 0xdd,
	0x8f, 0x2c, 0x72, 0x57, 0x6f, 0x65, 0x91, 0xdb, 0x10, 0xce, 0xfb, 0x39, 0xdc, 0xff, 0x6f, 0xe1,
	0x8e, 0xa1, 0xf0, 0xe7, 0xa3, 0x2c, 0x02, 0x7a, 0x85, 0x62, 0x62, 0x46, 0x17, 0x23, 0x1c, 0x3c,
	0xb9, 0x36, 0x21, 0xf8, 0x1a, 0xd5, 0x62, 0x3c, 0xc0, 0x55, 0x23, 0x87, 0xec, 0x9d, 0xc0, 0xde,
	0x9a, 0x60, 0x75, 0xa8, 0x01, 0x79, 0xfd, 0x79, 0xa8, 0x54, 0x67, 0xd1, 0x86, 0xad, 0x28, 0xc9,
	0x5c, 0x66, 0x43, 0x97, 0xc1, 0x2a, 0x58, 0x03, 0x76, 0xd6, 0x7e, 0xd0, 0x00, 0xfc, 0xbb, 0xb8,
	0x1d, 0x77, 0xee, 0xe3, 0xf2, 0xbf, 0x0c, 0x92, 0x26, 0xef, 0x5e, 0xc7, 0xad, 0x32, 0xa1, 0xbb,
	0x10, 0xc4, 0x9d, 0xdb, 0x9e, 0x1b, 0xe4, 0xce, 0x83, 0xc7, 0xa2, 0x90, 0xb2, 0x26, 0xfb, 0xb5,
	0xc5, 0x49, 0x3f, 0xbf, 0x7c, 0x31, 0xa7, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x4d, 0x79,
	0x7b, 0x4e, 0x02, 0x00, 0x00,
}
